### ISSUE TITLE
Nesting each-statement problem

### ISSUE THREAD

**Issue by kagemiku** [ryo33/LWTE.js#1]
# Nesting each-statement problem

> This engine doesn't support nesting each-statement.
# Comment
## Example

The following code doesn't work well in a php file using LWTE.js.

``` html
{each list}
Author: {author}<br/>
Issues: {each issues}{title}, {/each}<br/>
{/each}
```
## To be corrected contents

Please support nesting each-statement.

**Comment by ryo33** [comment]
```
lwte.addTemplate("a", "{each a}[{each b}({item}){/each}]{/each}");
lwte.useTemplate("a", {a: [{b: [{item: "e"}, {item: "f"}]}, {b: [{item: "g"}, {item: "h"}]}]}).should.be.exactly("[(e)(f)][(g)(h)]");
```

I added this test case and it works correctly.
Please show me failed templates and data structures.

**Comment by kagemiku** [comment]
I have checked my code just now.
And, I found that this issue is wrong.

I'm sorry to interrupt your works...
Please accept my apology for this wrong issue....
